version: '3.5'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - 5298:80

  apigrpc:
    image: apigrpc
    build:
      context: .
      dockerfile: Api.Grpc/Dockerfile
    ports:
      - 5111:5080
